language: perl
perl:
  - "5.18"
  - "5.26"

before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov

script:
  - perl Build.PL
  - ./Build build
  - cover -test

after_success:
  - travis_retry cover -report codecov
